language: objective-c
before_script:
    - brew update
    - brew upgrade xctool
script:
    - xctool -project NitroNSDictionaryCategories/NitroNSDictionaryCategories.xcodeproj -sdk iphonesimulator -scheme NitroNSDictionaryCategories test
