language: objective-c
before_script:
    - brew update
    - brew upgrade xctool
script:
	- cd NitroNSDictionaryCategories
    - xctool -project NitroNSDictionaryCategories.xcodeproj -sdk iphonesimulator -scheme NitroNSDictionaryCategories test
